services:
  ui:
    image: nodered/node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - "./src:/data"
  sdr:
    image: sdr
    build: ./sdr
    ports:
      - "8080:8080"
    devices:
      - "/dev/bus/usb/001/002:/dev/bus/usb/001/002"

