services:
  dashboard:
    image: local/dashboard
    build:
      context: ./build/nodered
      dockerfile: ../Dockerfile.nodered
    restart: always
    ports: 
      - 1880:1880
    depends_on:
      - dump1090
    volumes: 
      - run:/run/dump1090
      - data:/data
  dump1090:
    image: local/dump1090
    restart: always
    env_file: default.env
    build:
      context: ./build/dump1090
      dockerfile: ../Dockerfile.dump1090
    devices:
      - /dev/bus/usb
    volumes:
      - run:/run/dump1090
volumes:
  run:
  data:

